-- MySQL Script generated by MySQL Workbench
-- 11/06/14 17:52:59
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbreserveaqui
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbreserveaqui` DEFAULT CHARACTER SET latin1 ;
USE `dbreserveaqui` ;
-- -----------------------------------------------------
-- Table `dbreserveaqui`.`locadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbreserveaqui`.`locadora` (
  `idlocadora` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(16) NOT NULL,
  `rua` VARCHAR(150) NULL DEFAULT NULL,
  `numero` INT(11) NULL DEFAULT NULL,
  `complemento` VARCHAR(150) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `estado` CHAR(2) NULL DEFAULT NULL,
  `cep` CHAR(8) NULL DEFAULT NULL,
  `telefonecomercial` VARCHAR(15) NULL DEFAULT NULL,
  `telefonecontato` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `site` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idlocadora`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbreserveaqui`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbreserveaqui`.`filme` (
  `idfilme` INT(11) NOT NULL AUTO_INCREMENT,
  `idlocadora` INT(11) NOT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `foto` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idfilme`),
  INDEX `fk_filme_locadora1_idx` (`idlocadora` ASC),
  CONSTRAINT `fk_filme_locadora1`
    FOREIGN KEY (`idlocadora`)
    REFERENCES `dbreserveaqui`.`locadora` (`idlocadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbreserveaqui`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbreserveaqui`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbreserveaqui`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbreserveaqui`.`reserva` (
  `idreserva` INT(11) NOT NULL AUTO_INCREMENT,
  `idusuario` INT(11) NOT NULL,
  `idfilme` INT(11) NOT NULL,
  `situacao` ENUM('Pendente','Confirmado','Concluido','CanceladoUsuario','CanceladoLocadora') NOT NULL,
  `dtreserva` DATETIME NULL DEFAULT NULL,
  `dtconfirmada` DATETIME NULL DEFAULT NULL,
  `dtconcluido` DATETIME NULL DEFAULT NULL,
  `dtcancelado` DATETIME NULL DEFAULT NULL,
  `motivo` VARCHAR(255) NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_reserva_usuario` (`idusuario` ASC),
  INDEX `fk_reserva_filme1_idx` (`idfilme` ASC),
  CONSTRAINT `fk_reserva_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `dbreserveaqui`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reserva_filme1`
    FOREIGN KEY (`idfilme`)
    REFERENCES `dbreserveaqui`.`filme` (`idfilme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
