-- MySQL Script generated by MySQL Workbench
-- 09/18/14 21:00:59
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdReservaLocadora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdReservaLocadora` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bdReservaLocadora` ;

-- -----------------------------------------------------
-- Table `bdReservaLocadora`.`Filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdReservaLocadora`.`Filme` (
  `idFilme` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeFilme` VARCHAR(75) NOT NULL,
  `anoFilme` INT NOT NULL,
  `generoFilme` VARCHAR(45) NOT NULL,
  `diretorFilme` VARCHAR(75) NULL,
  `codigoFilme` INT UNSIGNED NOT NULL,
  `midiaFilme` VARCHAR(45) NULL,
  `sinopseFilme` VARCHAR(1000) NULL,
  `produtoraFilme` VARCHAR(45) NULL,
  `classificacaoIndicativaFilme` VARCHAR(45) NOT NULL,
  `valorPagoLocadora` DOUBLE NULL,
  `classificacaoValorFilme` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFilme`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
