-- MySQL Script generated by MySQL Workbench
-- 10/29/14 18:38:07
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdreserveaquei
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdreserveaquei` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bdreserveaquei` ;

-- -----------------------------------------------------
-- Table `bdreserveaquei`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdreserveaquei`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `perguntaDeSeguranca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdreserveaquei`.`Locadora1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdreserveaquei`.`Locadora1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdreserveaquei`.`FilmesLocadora1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdreserveaquei`.`FilmesLocadora1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `ano` INT NULL,
  `diretor` VARCHAR(45) NULL,
  `midia` VARCHAR(45) NOT NULL,
  `sinopse` VARCHAR(250) NULL,
  `produtora` VARCHAR(45) NULL,
  `classificacaoIndicativa` INT NULL DEFAULT 0,
  `valor` DOUBLE NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `generoFilme` VARCHAR(45) NOT NULL,
  `Locadora1_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_FilmesLocadora1_Locadora1_idx` (`Locadora1_id` ASC),
  CONSTRAINT `fk_FilmesLocadora1_Locadora1`
    FOREIGN KEY (`Locadora1_id`)
    REFERENCES `bdreserveaquei`.`Locadora1` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdreserveaquei`.`Locadora2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdreserveaquei`.`Locadora2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdreserveaquei`.`FilmesLocadora2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdreserveaquei`.`FilmesLocadora2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `ano` INT NULL,
  `diretor` VARCHAR(45) NULL,
  `midia` VARCHAR(45) NOT NULL,
  `sinopse` VARCHAR(250) NULL,
  `produtora` VARCHAR(45) NULL,
  `classificacaoIndicativa` INT NULL DEFAULT 0,
  `valor` DOUBLE NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `generoFilme` VARCHAR(45) NOT NULL,
  `Locadora2_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_FilmesLocadora2_Locadora21_idx` (`Locadora2_id` ASC),
  CONSTRAINT `fk_FilmesLocadora2_Locadora21`
    FOREIGN KEY (`Locadora2_id`)
    REFERENCES `bdreserveaquei`.`Locadora2` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdreserveaquei`.`integracaoLocadoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdreserveaquei`.`integracaoLocadoras` (
  `idIntegracao` INT NOT NULL AUTO_INCREMENT,
  `nomeTabelaFilms` VARCHAR(45) NOT NULL,
  `nomeLocadora` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idIntegracao`),
  UNIQUE INDEX `idIntegracao_UNIQUE` (`idIntegracao` ASC),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
